#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := mesh_touchpad
EXTRA_COMPONENT_DIRS := $(shell pwd)/touchpad_driver

include $(MDF_PATH)/project.mk
