#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := mdf_debug
EXTRA_COMPONENT_DIRS := $(shell pwd)/components

include $(MDF_PATH)/project.mk
