#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := $(notdir $(shell pwd))

EXTRA_COMPONENT_DIRS := ${MDF_PATH}/esp-idf/examples/peripherals/rmt/led_strip/components
include $(MDF_PATH)/project.mk
