#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := meshkit_sense
EXTRA_COMPONENT_DIRS := $(shell pwd)/sense_driver

include $(MDF_PATH)/project.mk
